networks:
  aiprojectorchestrator-network:
    driver: bridge

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: aiprojectorchestrator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aiprojectorchestrator-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Comment out the ports mapping when using host networking
    # ports:
    #   - "8087:8080"
    volumes:
      - ./Instructions:/app/Instructions
    depends_on:
      - db
    environment:
      - DB_HOST=localhost # Changed from 'db' since we're using host networking
      - DB_PORT=5432
      - DB_DATABASE=aiprojectorchestrator
      - DB_USER=user
      - DB_PASSWORD=password
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=aiprojectorchestrator;Username=user;Password=password
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: "host" # This bypasses Docker's SSL libraries entirely
    networks: [] # Remove from bridge network when using host mode

volumes:
  postgres_data:
