networks:
  aiprojectorchestrator-network:
    driver: bridge

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: aiprojectorchestrator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aiprojectorchestrator-network
    restart: unless-stopped

  nanogpt-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NANOGPT_API_KEY=${NANOGPT_API_KEY}
    networks:
      - aiprojectorchestrator-network
    restart: unless-stopped

volumes:
  postgres_data:
