networks:
  aiprojectorchestrator-network:
    driver: bridge

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: aiprojectorchestrator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aiprojectorchestrator-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    volumes:
      - ./Instructions:/app/Instructions
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=aiprojectorchestrator
      - DB_USER=user
      - DB_PASSWORD=password
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=aiprojectorchestrator;Username=user;Password=password
    networks:
      - aiprojectorchestrator-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    depends_on:
      - backend
    networks:
      - aiprojectorchestrator-network

volumes:
  postgres_data: